### ISSUE TITLE
Accessing Symphony

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#11]
Blocks #10 

Stanford's Symphony Web Services run behind a firewall so there is limited access. This ticket is to coordinate with Ops to figure out a strategy to allow Airflow instance to access these web services.

**Comment by jgreben** [comment]
however it’s coded, the info is basically this:

```
symws:
  url: https://symws-dev.stanford.edu/symws
  headers:
    sd-originating-app-id: SINOPIA_DEV
    x-sirs-clientID: SymWSStaffClient
  login_params:
    login: 'ask-libsys'
    password: 'ask libsys'
```
